### ISSUE TITLE
Unable to parse SOCK_ADDR

### ISSUE THREAD

**Issue by fraxken** [SlimIO/Winni#1]
Au sein de la structure IP_ADAPTER_ADDRESSES (structure renvoyé avec l'ensemble d'informations sur une interface réseau) il y a plusieurs champs contenant non pas une mais plusieurs IP représenté par des structures SOCKET_ADDR

https://docs.microsoft.com/en-us/windows/desktop/api/iptypes/ns-iptypes-_ip_adapter_addresses_lh

```
  PIP_ADAPTER_UNICAST_ADDRESS_LH     FirstUnicastAddress;
  PIP_ADAPTER_ANYCAST_ADDRESS_XP     FirstAnycastAddress;
  PIP_ADAPTER_MULTICAST_ADDRESS_XP   FirstMulticastAddress;
  PIP_ADAPTER_DNS_SERVER_ADDRESS_XP  FirstDnsServerAddress;
  SOCKET_ADDRESS                     Dhcpv6Server;
```

Je n'arrive pas à parser les IP retourner par la structure.

https://docs.microsoft.com/en-us/windows/desktop/api/ws2def/ns-ws2def-_socket_address

Il faudrait réussir à développer cet fonctionnalité pour débloquer le développement !

**Comment by AlexandreMalaj** [comment]
https://stackoverflow.com/questions/3989446/get-an-ip-address-string-from-getadaptersaddresses

https://docs.microsoft.com/fr-fr/windows/desktop/api/winsock2/nf-winsock2-wsaaddresstostringa

**Comment by fraxken** [comment]
Résolu !
